# Training Configuration
# Settings for YOLO detector fine-tuning

# Model
model:
  name: yolov12n  # yolov12n, yolov12s, yolov12m, yolov12l, yolov12x, yolov11n, yolov8n
  pretrained: true  # Use pretrained weights
  backbone_weights: null  # Path to distilled backbone (optional)

# Training hyperparameters
training:
  epochs: 100
  batch: 16
  imgsz: 640
  patience: 50  # Early stopping patience
  save_period: -1  # Save checkpoint every N epochs (-1 to disable)
  
  # Optimizer
  optimizer: auto  # auto, SGD, Adam, AdamW, NAdam, RAdam, RMSProp
  lr0: 0.01  # Initial learning rate
  lrf: 0.01  # Final learning rate (lr0 * lrf)
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  
  # Loss weights
  box: 7.5
  cls: 0.5
  dfl: 1.5
  
# Data augmentation
augmentation:
  hsv_h: 0.015  # Image HSV-Hue augmentation
  hsv_s: 0.7    # Image HSV-Saturation augmentation
  hsv_v: 0.4    # Image HSV-Value augmentation
  degrees: 0.0  # Image rotation (+/- deg)
  translate: 0.1  # Image translation (+/- fraction)
  scale: 0.5    # Image scale (+/- gain)
  shear: 0.0    # Image shear (+/- deg)
  perspective: 0.0  # Image perspective (+/- fraction)
  flipud: 0.0   # Image flip up-down probability
  fliplr: 0.5   # Image flip left-right probability
  mosaic: 1.0   # Image mosaic probability
  mixup: 0.0    # Image mixup probability
  copy_paste: 0.0  # Segment copy-paste probability

# Validation
validation:
  val: true  # Validate during training
  plots: true  # Save plots
  save_json: false  # Save results to JSON
  save_hybrid: false  # Save hybrid version (labels + predictions)
  conf: 0.001  # Object confidence threshold
  iou: 0.6    # IoU threshold for NMS
  max_det: 300  # Maximum detections per image

# Device and performance
device: ''  # CUDA device (empty for auto, 0 or 0,1,2,3 or cpu)
workers: 8  # Number of worker threads for dataloader
project: runs/detect  # Project directory
name: train  # Experiment name
exist_ok: false  # Overwrite existing experiment
pretrained: true  # Use pretrained model
verbose: true  # Verbose output
seed: 0  # Random seed for reproducibility
deterministic: true  # Deterministic mode
single_cls: false  # Train as single-class dataset
rect: false  # Rectangular training
cos_lr: false  # Cosine learning rate scheduler
close_mosaic: 10  # Disable mosaic X epochs before end
resume: false  # Resume from last checkpoint
amp: true  # Automatic Mixed Precision
fraction: 1.0  # Dataset fraction to train on
profile: false  # Profile ONNX and TensorRT speeds
freeze: null  # Freeze layers (list or int)

